// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://cheswepvjnxamltvfidk.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImNoZXN3ZXB2am54YW1sdHZmaWRrIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTAzNTMwNDcsImV4cCI6MjA2NTkyOTA0N30.2O4U71WzuLvUthNNzQyqshaTow7RZk9LVU_XHD9W9e0";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);